PMO_website/PMO/urls.py
from django.conf.urls import patterns, url

from PMO import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
	 url(r'^groups/$', views.homepage, name='groups'),
	 url(r'^(?P<i_id>\d+)/$', views.archive, name='archive'),
	 url(r'^login/$', views.login_user, name='login_user'),
	 url(r'^login/a/$', views.logged_user, name='login'),
	 url(r'^login/submit/$', views.submit, name='login'),
	url(r'^logout/$', views.logout_user, name='logout_user'),	
	
)

PMO_website/PMO_website/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'PMO_website.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^submit/', include('submit.urls',namespace="submit")),
	url(r'^PMO/', include('PMO.urls',namespace="PMO")),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PMO_website/submit/urls.py
from django.conf.urls import patterns, url

from submit import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='submit'),
	
	url(r'^(?P<group_id>\d+)/$', views.detail, name='detail'),
	url(r'^list/$', views.list, name='list'),
	
	#url(r'^add/$', views.index, name='index'),
)

PMO_website/PMO/models.py
from django.db import models

# Create your models here.
from django.db import models
import datetime
import os
#from django.utils import timezone
from datetime import datetime


class User(models.Model):
	recent_upload = models.TextField(max_length=500, null=True, blank=True)
	
	pub_date = models.DateTimeField('date published', null=True, blank=True)
	user_name = models.CharField(max_length=200, null=True, blank=True)
	
class Question(models.Model):
	question_id = models.AutoField(max_length=1000,primary_key=True)
        question = models.TextField(null=False,blank=False)
	ques_date = models.DateTimeField()
	userr = models.ForeignKey(User) 

	def __str__(self):             
            return self.question

class Post(models.Model):
        ques_id = models.ForeignKey(Question)    
	userr = models.ForeignKey(User)  
	post = models.TextField(max_length=500, null=True, blank=True)
	post_date = models.DateTimeField()

	def __str__(self):             
            return self.post

PMO_website/submit/models.py
from django.db import models

# Create your models here.
from django.db import models
import datetime
import os
from django.utils import timezone
from datetime import datetime


def file(self, filename):
	url = "documents/groups/%s/%s" %(self.group_name, filename)
	
	return url

def hashed_uploads_dirs(instance, filename):
    """Returns path with md5 hash as directory"""
    return os.path.join(instance.md5, filename)




class Groups(models.Model):
	group_name = models.CharField(max_length=200)
	sub_date = models.DateTimeField('date published',null=True, blank=True)
	
	published = models.CharField(max_length=255, null=True, blank=True)
	
	docfile = models.FileField(upload_to=file,null=True, blank=True)		
	
	md5 = models.CharField(max_length=32,null=True, blank=True)
	summary = models.TextField(max_length=500, null=True, blank=True)
	src_url = models.URLField(null=True, blank=True)
	doc_url = models.URLField(null=True, blank=True)
	
	def file_location(self):
		return self.docfile
				
		
	def __str__(self):              # __unicode__ on Python 2
		return self.group_name
		
	
		
	
class Partners(models.Model):
	group = models.ForeignKey(Groups)
	partner_name = models.CharField(max_length=200,null=True, blank=True)
	
	
	def __str__(self):              # __unicode__ on Python 2
		return self.partner_name


	
		

PMO_website/submit/forms.py
from django import forms
 
from submit.models import Groups
 
 
class UploadFileForm(forms.Form):
     
    class Meta:
        model = Groups
		

PMO_website/PMO/views.py
from django.shortcuts import render, render_to_response
from django.contrib.auth import authenticate, login, logout
# Create your views here.

from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from PMO.models import User


def index(request):
	return render(request,'PMO/index.html')
	
	
def homepage(request):
	
	
	home = User.objects.order_by('id').reverse()[:10]
	
	#obj_list = []
	#obj_list1 = []
	
	#for i in home:
		#obj_list.append(i)
		
	#obj_list1 = reversed(obj_list) 
	
	d = User.objects.latest('id')	 
				   
	#return render(request, 'PMO/announcement.html',{'home':obj_list1, 'd':d})
	return render(request, 'PMO/PMO.html',{'home':home, 'd':d})	
	
def submit(request):
	if request.method == 'POST':
		r = User(recent_upload = request.POST['anc'],pub_date = request.POST['date1'], user_name = request.POST['user_name'])
		
		r.save()
		#return render(request,'PMO/loggedin.html')
		return render(request,'PMO/user_home.html')	
	else:
	 	return render(request,'PMO/user_home.html')	
	
def archive(request,i_id):
	p = User.objects.get(pk=i_id)
	
	#return HttpResponse(p.recent_upload)
	return render(request, 'PMO/archive.html', {'p':p})

def login_user(request):
	return render(request, 'PMO/authenticate.html')
		
def logged_user(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				#return render(request,'PMO/loggedin.html',{'user':user})
				return render(request,'PMO/user_home.html',{'user':user})
				
		else:
				return HttpResponse('User is not valid')		
	else:
		return render(request,'PMO/user_home.html')




def logout_user(request):
	logout(request)
	return render(request,'PMO/authenticate.html')			
	

PMO_website/submit/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from submit.models import Groups, Partners
from django.template import RequestContext
from django.core.files.base import ContentFile
from django.core.files import File
from submit.forms import UploadFileForm





def index(request):
	#groups = Groups.objects.all()
	#return render(request, 'submit/form.html', {'groups':groups})
	
	if request.method == 'POST':
		form = UploadFileForm(request.POST, request.FILES)
		if form.is_valid():
			#r = Groups(docfile = request.FILES['file_id'])
			#r.save()
			
			r = Groups(group_name=request.POST['projName'],summary=request.POST['summary'],src_url=request.POST['srcurl'],doc_url=request.POST['docurl'],docfile = request.FILES['file_id'],sub_date=request.POST['date2'])
			r.save()
			#a = Partners(partner_name=request.POST['p1'],group=r)
			#a.save()
			#b= Partners(partner_name=request.POST['p2'],group=r)
			#b.save()
			#c= Partners(partner_name=request.POST['p3'],group=r)
			#c.save()
			
			
			 
		
			#return render_to_response(request, 'submit/result.html', {'r': r})
			#return render_to_response(request, 'submit/result.html',{'form':form})
			#return HttpResponse("Form has been submitted")
			return render(request,'PMO/user_home.html',{'submitted':"Form submitted successfully"})
	else:
		form = UploadFileForm()
 
		data = {'form': form}
		return render_to_response('submit/form.html', data, context_instance=RequestContext(request))



def detail(request, group_id):
	form = DocumentForm()
	doc = Groups.objects.get(pk=group_id)
	return render_to_response(
        'submit/result.html',
        {'doc': doc, 'form': form},
        context_instance=RequestContext(request)
    )

def list(request):
	projects = Groups.objects.all()
	return render_to_response('submit/list.html',{'projects':projects})
    



def add(request):
	
	r = Groups(group_name=request.POST['projName'],summary=request.POST['summary'],src_url=request.POST['srcurl'],doc_url=request.POST['docurl'])
	r.save()
	a = Partners(partner_name=request.POST['p1'],group=r)
	a.save()
	b= Partners(partner_name=request.POST['p2'],group=r)
	b.save()
	c= Partners(partner_name=request.POST['p3'],group=r)
	c.save()
	
	

	
	return render(request, 'submit/result.html', {'r': r})
	
	

PMO_website/PMO/templates/PMO/PMO.html
<!DOCTYPE html>
<html lang="en">

<head>
	
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Expand, contract, animate forms with jQuery wihtout leaving the page" />
    <meta name="keywords" content="expand, form, css3, jquery, animate, width, height, adapt, unobtrusive javascript"/>
    
	<title>PMO</title>

	<!-- Calling main css file-->
	<link rel="stylesheet" href="../../static/login/css/teams.css">
   	
	<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
	<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    
    <!-- jQuery lib for mouse wheel horizontal scroll-->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="../../static/js/jquery.mousewheel.js"></script>
    
           
	 <!--	<link rel="shortcut icon" href="../favicon.ico" type="image/x-icon"/>
      <link rel="stylesheet" type="text/css" href="../static/login/css/style.css" /> 
		<script src="../static/login/js/cufon-yui.js" type="text/javascript"></script>
		<script src="../static/login/js/ChunkFive_400.font.js" type="text/javascript"></script> 
        
		<script type="text/javascript">
			Cufon.replace('h1',{ textShadow: '1px 1px #fff'});
			Cufon.replace('h2',{ textShadow: '1px 1px #fff'});
			Cufon.replace('h3',{ textShadow: '1px 1px #000'});
			Cufon.replace('.back');
		</script> -->
    	
    <!--Enabling horizontal scroll using mouse wheel -->
    <script>
	$(document).ready(function() {
    
	$('html, body, *').mousewheel(function(e, delta) {
        this.scrollLeft -= (delta * 100);
        e.preventDefault();
    });
	
	
	});
	</script>
    
       
    <script>
		function funReset() {
    	document.getElementById("updateProject").reset();
	}
	</script>
    
    <script>
		function funSubmit(){
		document.getElementById("updateProject").submit();		
	}
	
	</script>
    
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript">

$(function(){

// The height of the content block when it's not expanded
var adjustheight = 100;
// The "more" link text
var moreText = "+  More";
// The "less" link text
var lessText = "- Less";

// Sets the .more-block div to the specified height and hides any content that overflows
$(".more-less .more-block").css('height', adjustheight).css('overflow', 'hidden');

// The section added to the bottom of the "more-less" div
$(".more-less").append('<p class="continued">[&hellip;]</p><a href="#" class="adjust"></a>');

$("a.adjust").text(moreText);

$(".adjust").toggle(function() {
		$(this).parents("div:first").find(".more-block").css('height', 'auto').css('overflow', 'visible');
		// Hide the [...] when expanded
		$(this).parents("div:first").find("p.continued").css('display', 'none');
		$(this).text(lessText);
	}, function() {
		$(this).parents("div:first").find(".more-block").css('height', adjustheight).css('overflow', 'hidden');
		$(this).parents("div:first").find("p.continued").css('display', 'block');
		$(this).text(moreText);
});
});

</script>

<style>
	/*body{
		background:#fefefe;
		font-family:Tahoma, Geneva, sans-serif; 
	}
	p{
		font-family:Tahoma, Geneva, sans-serif; 
		font-size:14px; 
		line-height:20px;
		margin-bottom:20px;
	}
	#container{
		width:300px;
		margin : auto;
		
	} */
	a.adjust{
		padding:10px;
		display:block;
		font-weight:bold;
		background:#eee;
		color:#333;
		border-radius:12px;
		-webkit-border-radius:12px;
		-moz-border-radius:12px;
		width:80px;
		text-align:center;
		text-decoration:none;
	}
		a.adjust:hover{
			background:#333;
			color:#FFF;
			-webkit-transition: all 400ms; 
			-moz-transition: all 400ms ease; 
			-o-transition: all 400ms ease; 
			transition: all 400ms ease;
		} /*
	p.continued{
		margin-top:0;
	}
	img{
		padding:10px;
		background:#FFF;
		border-radius: 12px;
		-webkit-box-shadow: 0 1px 13px rgba(0,0,0,.25);
		-moz-box-shadow: 0 1px 13px rgba(0,0,0,.25);
		box-shadow: 0 1px 13px rgba(0,0,0,.25);
		width:400px;
		margin-left:20px;
	}
	link
	{
		 height : 100px;
		 
	}*/
	
	


	
</style>



</head>

<body >

			<nav>
                <ul>
                	<li>
  							<img src="../../static/images/logo.png">
                    </li>
                    <li>
                    	<a href="#index.html">Home</a>
                    </li>
                    <li>
                    	<a href="#divWorks">Our Works</a>
                    </li>
                    <li>
                    	<a href="#divAbout">About PMO</a>
                    </li>
                    <li>
                    	<a href="{% url 'submit:list'%}">Documentation</a>
                    </li>
                    <li>
                    	<a href="#lastDiv">Learn</a>
                    </li>
                    <li>
                    	<a href="#divContact">Reach Us</a>
                    </li>
					<li>
                    	<a href= "/PMO/login/" target="_blank">Sign In</a>
                    </li>
                  
                </ul>
               
            </nav>
            
        <h3 style="text-align:center; background-color:#FFF; margin-top:3em; color:#03F;"> Team - PMO MOOCs </h3>
     
<div class="pmoMoocHome" id="pmoMooc">

 <h3 style="text-align:center; background-color:#9CF; margin-top:auto; color:#000;"> Notification </h3>
 
            <font size="2"><p align="left">{{d.recent_upload}}</p></font>
      
 </div>
  
  
<div class="pmoMoocArchive"  id="pmoArchive">
<div id="container">
  <div class="more-less">
    
   <div class="more-block">
 <h3 style="text-align:center; background-color:#9CF; margin-top:auto; color:#000;"> Recent Notifications </h3>

{% for i in home %}

 
  <li><p align="left"><a href="/PMO/{{ i.id }}/" target="_blank"><font size="2">{{ i.pub_date }} <i>by</i> <b>{{ i.user_name }}</b></font></a></p></li>
  
  {% endfor %} 
  </div>
  </div>
</div>
 
</div>
  
    <div class="footer">
    
    <img src="../../static/images/mhrd-logo.png" style="position: absolute; margin: 0 auto;
       top:0px; left: 50px; width: 80px; height: 60px;">
    				
    <img src="../../static/images/nmeict-logo.png" style="position: absolute; margin: 0 auto;
       top:0px; right: 50px; width: 80px; height: 60px;">
								
    <div class="col-lg-4" id="social" style="z-index:2">
		
        <div id="social-icons">
       
        <a href="https://github.com/" target="_blank">
          <img src="../../static/images/github-white.png" style="position: absolute; top:-20px; left: 560px; width: 48px; height: 48px;" alt="github">
        </a>
        <a href="https://plus.google.com/">
          <img src="../../static/images/googleplus.png" style="position: absolute; margin: 0 auto;
       top:-20px; left: 620px; width: 48px; height: 48px; " alt="googleplus">
        </a>
        <a href="#">
          <img src="../../static/images/facebook.png" style="position: absolute; margin: 0 auto;
       top:-20px; left: 680px; width: 48px; height: 48px; " alt="facebook">
        </a>
        <a href="#" target="_blank">
          <img src="../../static/images/youtube.png" style="position: absolute; margin: 0 auto;
       top:-20px; left: 740px; width: 48px; height: 48px; " alt="youtube">
        </a>
        
		</div>
    </div>      

  </div>
</div>
     
</body>
</html>

PMO_website/PMO/templates/PMO/archive.html
{{p.recent_upload}}

PMO_website/PMO/templates/PMO/loggedin.html
<html>
<head> 
<script type="text/javascript" language="javascript">
window.history.forward(1);
document.attachEvent("onkeydown", my_onkeydown_handler);
function my_onkeydown_handler()
{
switch (event.keyCode)
{
case 116 : // F5;
event.returnValue = false;
event.keyCode = 0;
window.status = "We have disabled F5";
break;
}
}
</script>
</head>
<body>
<p>Congratulation {{user.username}}.. You have been successfully logged in </p>
<h2>Make a new Announcement here</h2>
 <div class="projectUpdate">
 <form action="/PMO/" method="post" enctype="multipart/form-data">
 {% csrf_token %}
 <p><textarea rows="4" name="anc" placeholder="Make a announcement here" style="width:70%"></textarea>
  </p>

  <input type="hidden" id="date1" name="date1">  
   <input type="hidden" id="user" name="user_name" value = "{{user.username}}" >
     
 <script type="text/javascript">
 function myFunction(){
	 var d = new Date();
    var curr_date = d.getDate();
    var curr_month = d.getMonth() + 1; //Months are zero based
    var curr_year = d.getFullYear();
	var h = d.getHours();
    var m = d.getMinutes();
    var s = d.getSeconds();
	

	document.getElementById("date1").value = curr_year + "-" + curr_month + "-" + curr_date + " " +  h + ":" + m + ":" + s;
		     
 }
 </script>

  
      										
  <input type="submit" onclick="myFunction()" value="upload" />
  
    </form>
</div>
<a href="{% url 'submit:submit' %}" target="_blank">fill form</a>
<a href ="/PMO/logout/">logout</a>
</body>
</html>

PMO_website/PMO/templates/PMO/login.html
<!DOCTYPE html>
<html>
<head> 
<script type="text/javascript" language="javascript">
window.history.forward(1);
document.attachEvent("onkeydown", my_onkeydown_handler);
function my_onkeydown_handler()
{
switch (event.keyCode)
{
case 116 : // F5;
event.returnValue = false;
event.keyCode = 0;
window.status = "We have disabled F5";
break;
}
}
</script>
</head>
<body>
 
    <div id="login">
        <form class="form-horizontal" name="LoginForm" action="/PMO/login/" method="post">
        {% csrf_token %}
           <p> <label class="control-label" for="username">Username</label>
            
                <input type="text" id="username" name="username"  placeholder="Username">
            </p>
        <p>
            <label class="control-label" for="password">Password</label>
            
                <input type="password" name="password" id="password" placeholder="Password">
           </p> 
    
                <button type="submit" class="btn">Login</button>
         
      
        </form>
        
    </div>
    
   
    
</body>
</html>

PMO_website/PMO/templates/PMO/user_home.html
<!DOCTYPE html>
<html lang="en">

<head>
<script type="text/javascript" language="javascript">
window.history.forward(1);
document.attachEvent("onkeydown", my_onkeydown_handler);
function my_onkeydown_handler()
{
switch (event.keyCode)
{
case 116 : // F5;
event.returnValue = false;
event.keyCode = 0;
window.status = "We have disabled F5";
break;
}
}
</script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="Expand, contract, animate forms with jQuery wihtout leaving the page" />
    <meta name="keywords" content="expand, form, css3, jquery, animate, width, height, adapt, unobtrusive javascript"/>
    
	<title>PMO-UserHomePage</title>

	<!-- Calling main css file-->
	<link rel="stylesheet" href="../../../static/login/css/main.css">
   	
	<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
	<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    
    <!-- jQuery lib for mouse wheel horizontal scroll-->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="../../../static/js/jquery.mousewheel.js"></script>
    
     <script type="text/javascript" src="../../../static/tinymce/tinymce.min.js"></script>
     
     <script type="text/javascript">
tinymce.init({
    selector: "#txtarea",
    theme: "modern",
	inline: false,
	forced_root_block: "",
invalid_elements: "strong, em, span, h1,h2,h3, style",
    plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
    templates: [
        {title: 'Test template 1', content: 'Test 1'},
        {title: 'Test template 2', content: 'Test 2'}
    ]
});
</script>
    
        
    <!--Enabling horizontal scroll using mouse wheel -->
    <script>
	$(document).ready(function() {
    
	$('html, body, *').mousewheel(function(e, delta) {
        this.scrollLeft -= (delta * 100);
        e.preventDefault();
    });
	
	
	});
	</script>
    
       
    <script>
		function funReset() {
    	document.getElementById("updateProject").reset();
	}
	</script>
    
    <script>
		function funSubmit(){
		document.getElementById("updateProject").submit();		
	}
	
	</script>
    
    	
</head>

<body>

			<nav>
                <ul>
                	<li>
  							<img src="../../../static/images/logo.png">
                    </li>
                    <li>
                    	<a href="#usrHome">Home</a>
                    </li>
                    
                    <li>
                    	<a href="#updateProject">Upload Document</a>
                    </li>
                   
                    
					
                    <li>
                    	<a href="/PMO/logout/">Sign Out</a>
                    </li>
                </ul>
               
            </nav>
            
<div class="userHome" id="usrHome">

<form action="/PMO/login/submit/" method="post" enctype="multipart/form-data">
 {% csrf_token %}
			<h4 style="color:#0FF">You have beeen logged in as {{user.username}} </h4>

    		<textarea class="txtarea" id="txtarea" name="anc" style="width:100%; height:300px"></textarea>
            <input type="hidden" id="date1" name="date1">
            <input type="hidden" id="user" name="user_name" value = "{{user.username}}" >
     
 <script type="text/javascript">
 function myFunction(){
	 var d = new Date();
    var curr_date = d.getDate();
    var curr_month = d.getMonth() + 1; //Months are zero based
    var curr_year = d.getFullYear();
	var h = d.getHours();
    var m = d.getMinutes();
    var s = d.getSeconds();
	

	document.getElementById("date1").value = curr_year + "-" + curr_month + "-" + curr_date + " " +  h + ":" + m + ":" + s;
		     
 }
 </script>

           
    		<input type="submit" name="Submit" onClick="myFunction()" value="Submit" style="width: 100px; vertical-align:middle; float:none; display: 		table-cell"/>
            
           
    
		</form>

</div>

<div class="projectUpdate" id="updateProject">
 <h4 style="color:#00F">{{ submitted }} </h4>
 
 
 	<form action="{% url 'submit:submit' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
 <p>	<label id="labels">Project Name</label> <input type="text" name="projName" autofocus id="inputbox" placeholder="Enter the name of your project" >
 </p>
 <input type="hidden" id="date2" name="date2">
 <script type="text/javascript">
 function myFunction2(){
	 var d = new Date();
    var curr_date = d.getDate();
    var curr_month = d.getMonth() + 1; //Months are zero based
    var curr_year = d.getFullYear();
	var h = d.getHours();
    var m = d.getMinutes();
    var s = d.getSeconds();
	

	document.getElementById("date2").value = curr_year + "-" + curr_month + "-" + curr_date + " " +  h + ":" + m + ":" + s;
		     
 }
 </script>
 
  <p>  <label id="labels">Summary</label><textarea rows="4" name="summary" placeholder="Enter brief summary of the project" style="width:70%"></textarea>
  </p>
  <p><label id="labels">Source url</label><input type="text" name="srcurl" id="inputbox" placeholder="Enter the source url">
  </p>  
  <p><label id="labels">Doc url</label><input type="text" name="docurl" id="inputbox" placeholder="Enter the document url">
  </p>    
  <p><label id="labels">Upload Apk</label><input type="file" name="file_id" id="inputbox" /></p>
 
  
  <p><input type="submit" name="btnSubmit" onClick="myFunction2()" value="Submit" id="button" />
  
  <input type="reset" name="btnReset" value="Clear" id="button" onclick="funReset()" /></p>  
  
   	</form>
    
</div> 	    
  
  <div class="footer">
    
    <img src="../../../static/images/mhrd-logo.png" style="position: absolute; margin: 0 auto;
       top:0px; left: 50px; width: 80px; height: 60px;">
    				
    <img src="../../static/images/nmeict-logo.png" style="position: absolute; margin: 0 auto;
       top:0px; right: 50px; width: 80px; height: 60px;">
								
    <div class="col-lg-4" id="social" style="z-index:2">
		
        <div id="social-icons">
       
        <a href="https://github.com/" target="_blank">
          <img src="../../../static/images/github-white.png" style="position: absolute; top:-20px; left: 560px; width: 48px; height: 48px;" alt="github">
        </a>
        <a href="https://plus.google.com/">
          <img src="../../../static/images/googleplus.png" style="position: absolute; margin: 0 auto;
       top:-20px; left: 620px; width: 48px; height: 48px; " alt="googleplus">
        </a>
        <a href="#">
          <img src="../../../static/images/facebook.png" style="position: absolute; margin: 0 auto;
       top:-20px; left: 680px; width: 48px; height: 48px; " alt="facebook">
        </a>
        <a href="#" target="_blank">
          <img src="../../../static/images/youtube.png" style="position: absolute; margin: 0 auto;
       top:-20px; left: 740px; width: 48px; height: 48px; " alt="youtube">
        </a>
        
		</div>
    </div>      

  </div>
</div>
     
</body>
</html>

PMO_website/submit/templates/submit/form.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; 		charset=utf-8" />
<title>PMO</title>
	    
</head>

<body>
 
 <div class="projectUpdate">
 


 	<form action="/submit/" method="post" enctype="multipart/form-data">
 
 {% csrf_token %}
 <p>	<label id="labels">Project Name</label> <input type="text" name="projName" autofocus id="inputbox" placeholder="Enter the name of your project" >
 </p>
 <p><input type="date" name="bday"></p>
  <p>	<label id="labels">Partner 1</label> <input type="text" name="p1" autofocus id="inputbox" placeholder="Enter the name of your project" >
 </p>
   <p>	<label id="labels">Partner 2</label> <input type="text" name="p2" autofocus id="inputbox" placeholder="Enter the name of your project" >
 </p>
   <p>	<label id="labels">Partner 3</label> <input type="text" name="p3" autofocus id="inputbox" placeholder="Enter the name of your project" >
 </p>
 <p>  <label id="labels">Summary</label><textarea rows="4" name="summary" placeholder="Enter brief summary of the project" style="width:70%"></textarea>
  </p>
  <p><label id="labels">Source url</label><input type="text" name="srcurl" id="inputbox" placeholder="Enter the source url">
  </p>  
  <p><label id="labels">Doc url</label><input type="text" name="docurl" id="inputbox" placeholder="Enter the document url">
  </p>       
  <p><label id="labels">Upload Apk</label><input type="file" name="file_id" id="inputbox" /></p>
  <p><label id="labels">Upload Logo</label><input type="file" name="logo_id" id="inputbox" /></p>
  <input type="submit" value="send" />
  
    </form>

  <a href="{% url 'submit:list' %}" >list all the projects</a>
    </div>
    
</body>
</html>